<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PLT>
<PLT_API DOC_VERSION="22.1.0">
    <ITEMS_LIST>
        <ITEM type="mem">
            <UNIT>s</UNIT>
            <DATA>AAAAyQAAAAAAAAAAP7mZmZmZmao/yZmZmZmZqj/TMzMzMzNAP9mZmZmZmao/4AAAAAAACj/jMzMzMzM/P+ZmZmZmZnQ/6ZmZmZmZqT/szMzMzMzeP/AAAAAAAAo/8ZmZmZmZpT/zMzMzMzNAP/TMzMzMzNs/9mZmZmZmdj/4AAAAAAARP/mZmZmZmaw/+zMzMzMzRz/8zMzMzMziP/5mZmZmZn1AAAAAAAAADEAAzMzMzMzZQAGZmZmZmaZAAmZmZmZmc0ADMzMzMzNAQAQAAAAAAA1ABMzMzMzM2kAFmZmZmZmnQAZmZmZmZnRABzMzMzMzQUAIAAAAAAAOQAjMzMzMzNtACZmZmZmZqEAKZmZmZmZ1QAszMzMzM0JADAAAAAAAD0AMzMzMzMzcQA2ZmZmZmalADmZmZmZmdkAPMzMzMzNDQBAAAAAAAAhAEGZmZmZmb0AQzMzMzMzWQBEzMzMzMz1AEZmZmZmZpEASAAAAAAALQBJmZmZmZnJAEszMzMzM2UATMzMzMzNAQBOZmZmZmadAFAAAAAAADkAUZmZmZmZ1QBTMzMzMzNxAFTMzMzMzQ0AVmZmZmZmqQBYAAAAAABFAFmZmZmZmeEAWzMzMzMzfQBczMzMzM0ZAF5mZmZmZrUAYAAAAAAAUQBhmZmZmZntAGMzMzMzM4kAZMzMzMzNJQBmZmZmZmbBAGgAAAAAAF0AaZmZmZmZ+QBrMzMzMzOVAGzMzMzMzTEAbmZmZmZmzQBwAAAAAABpAHGZmZmZmgUAczMzMzMzoQB0zMzMzM09AHZmZmZmZtkAeAAAAAAAdQB5mZmZmZoRAHszMzMzM60AfMzMzMzNSQB+ZmZmZmblAIAAAAAAAEEAgMzMzMzNDQCBmZmZmZnZAIJmZmZmZqUAgzMzMzMzcQCEAAAAAAA9AITMzMzMzQkAhZmZmZmZ1QCGZmZmZmahAIczMzMzM20AiAAAAAAAOQCIzMzMzM0FAImZmZmZmdEAimZmZmZmnQCLMzMzMzNpAIwAAAAAADUAjMzMzMzNAQCNmZmZmZnNAI5mZmZmZpkAjzMzMzMzZQCQAAAAAAAxAJDMzMzMzP0AkZmZmZmZyQCSZmZmZmaVAJMzMzMzM2EAlAAAAAAALQCUzMzMzMz5AJWZmZmZmcUAlmZmZmZmkQCXMzMzMzNdAJgAAAAAACkAmMzMzMzM9QCZmZmZmZnBAJpmZmZmZo0AmzMzMzMzWQCcAAAAAAAlAJzMzMzMzPEAnZmZmZmZvQCeZmZmZmaJAJ8zMzMzM1UAoAAAAAAAIQCgzMzMzMztAKGZmZmZmbkAomZmZmZmhQCjMzMzMzNRAKQAAAAAAB0ApMzMzMzM6QClmZmZmZm1AKZmZmZmZoEApzMzMzMzTQCoAAAAAAAZAKjMzMzMzOUAqZmZmZmZsQCqZmZmZmZ9AKszMzMzM0kArAAAAAAAFQCszMzMzMzhAK2ZmZmZma0ArmZmZmZmeQCvMzMzMzNFALAAAAAAABEAsMzMzMzM3QCxmZmZmZmpALJmZmZmZnUAszMzMzMzQQC0AAAAAAANALTMzMzMzNkAtZmZmZmZpQC2ZmZmZmZxALczMzMzMz0AuAAAAAAACQC4zMzMzMzVALmZmZmZmaEAumZmZmZmbQC7MzMzMzM5ALwAAAAAAAUAvMzMzMzM0QC9mZmZmZmdAL5mZmZmZmkAvzMzMzMzNQDAAAAAAAABAMBmZmZmZmkAwMzMzMzM0QDBMzMzMzM5AMGZmZmZmaEAwgAAAAAACQDCZmZmZmZxAMLMzMzMzNkAwzMzMzMzQQDDmZmZmZmpAMQAAAAAABEAxGZmZmZmeQDEzMzMzMzhAMUzMzMzM0kAxZmZmZmZsQDGAAAAAAAZAMZmZmZmZoEAxszMzMzM6QDHMzMzMzNRAMeZmZmZmbkAyAAAAAAAIQDIZmZmZmaJAMjMzMzMzPEAyTMzMzMzWQDJmZmZmZnBAMoAAAAAACkAymZmZmZmkQDKzMzMzMz5AMszMzMzM2EAy5mZmZmZyQDMAAAAAAAxAMxmZmZmZpkAzMzMzMzNAQDNMzMzMzNpAM2ZmZmZmdEAzgAAAAAAOQDOZmZmZmahAM7MzMzMzQkAzzMzMzMzcQDPmZmZmZnZANAAAAAAAAA==</DATA>
            <NAME>A0</NAME>
        </ITEM>
        <ITEM type="mem">
            <UNIT>m/s/s</UNIT>
            <DATA>AAAAyQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/+fTNgaIJPEACC3MSrZOgQAPofAffX/RABJfKCNg+e0AE2AbFV8BCQATvV4Y+Ea1ABPeKce4ZJUAE+h3IwE6/QAT6j4XG7yBABPoonuz0EUAE+WIWlLdlQAT4aGvOjPpABPdMDIlU7EAE9hL16i1TQAT0v3KD4dlABPNSVsktnkAE8cv86n3AQATwLIIOTw9ABO5z9+vUokAE7KJuvEqKQATqt++a065ABOi0gjd+aEAE5pgw+FtTQATkYwY+oWtABOIVDLTSH0AE365PZN4HQATdLtnNS25ABNqWt+D7sEAE1+X2AxzNQATVHKEIcq1ABNI6xkOAHEAEz0BzVDxVQATMLbZ0DS1ABMkCnkFz/UAExb85x8e4QATCY5iC2uVABL7vymK6yEAEuRh/Hvq4QASt1Y+LJQpABKBeQmBfuUAEkg4NZHYIQASDZYygDSxABHST+e0nQEAEZasKvN2QQARWsWen7KhABEeppzx8VkAEOJTq/nCCQAQpc8WB/6hABBpGj0D5UkAEB3F8BxP5QAPUtul5EZBAA5CX5UBHq0ADRrCNME7hQAL7VLkoIvJAArAf9wPtLUACZakjECX4QAIcJwTkvABAAdOreWjxhEABjDtB5CL7QAFF1e8QLVFAAQB5P+bnOEAAvCJK6uIMQAB4zeE1QzFAADZ4wzHR9j//6j9bK005P/9pfr8qaRk//uqpPSOxcj/+bbhuRM/lP/3ypfrKYI4//XlrluHxbD/9AgMC2Ug2P/yMZhE9Rlg//BiOnZrC1z/7pnaUXCRsP/s2F/EJ8xg/+sdsvAzICz/6Wm8JD1ZEP/nvGQINScA/+YVk3cvEoz/5HUziRPdsP/i2yziniak/+FxP5trUCj/4F+7jyrrPP/fcdSIhTGo/96SLMimq6T/3bjXn6PG3P/c4uVyjIyk/9wPPGN1uGj/2z10fN6TWP/abWTBS5c8/9me/QmdsQz/2NI1wXtoDP/YBwsKa57U/9c9ej1lZwT/1nWAgsNXtP/VrxuVTBps/9TqSU5HrfD/1CcHfuJIzP/TZVPxcUiY/9KlLG65PTQ==</DATA>
            <NAME>A1</NAME>
        </ITEM>
        <ITEM type="mem">
            <UNIT>s</UNIT>
            <DATA>AAAAyQAAAAAAAAAAP7mZmZmZmao/yZmZmZmZqj/TMzMzMzNAP9mZmZmZmao/4AAAAAAACj/jMzMzMzM/P+ZmZmZmZnQ/6ZmZmZmZqT/szMzMzMzeP/AAAAAAAAo/8ZmZmZmZpT/zMzMzMzNAP/TMzMzMzNs/9mZmZmZmdj/4AAAAAAARP/mZmZmZmaw/+zMzMzMzRz/8zMzMzMziP/5mZmZmZn1AAAAAAAAADEAAzMzMzMzZQAGZmZmZmaZAAmZmZmZmc0ADMzMzMzNAQAQAAAAAAA1ABMzMzMzM2kAFmZmZmZmnQAZmZmZmZnRABzMzMzMzQUAIAAAAAAAOQAjMzMzMzNtACZmZmZmZqEAKZmZmZmZ1QAszMzMzM0JADAAAAAAAD0AMzMzMzMzcQA2ZmZmZmalADmZmZmZmdkAPMzMzMzNDQBAAAAAAAAhAEGZmZmZmb0AQzMzMzMzWQBEzMzMzMz1AEZmZmZmZpEASAAAAAAALQBJmZmZmZnJAEszMzMzM2UATMzMzMzNAQBOZmZmZmadAFAAAAAAADkAUZmZmZmZ1QBTMzMzMzNxAFTMzMzMzQ0AVmZmZmZmqQBYAAAAAABFAFmZmZmZmeEAWzMzMzMzfQBczMzMzM0ZAF5mZmZmZrUAYAAAAAAAUQBhmZmZmZntAGMzMzMzM4kAZMzMzMzNJQBmZmZmZmbBAGgAAAAAAF0AaZmZmZmZ+QBrMzMzMzOVAGzMzMzMzTEAbmZmZmZmzQBwAAAAAABpAHGZmZmZmgUAczMzMzMzoQB0zMzMzM09AHZmZmZmZtkAeAAAAAAAdQB5mZmZmZoRAHszMzMzM60AfMzMzMzNSQB+ZmZmZmblAIAAAAAAAEEAgMzMzMzNDQCBmZmZmZnZAIJmZmZmZqUAgzMzMzMzcQCEAAAAAAA9AITMzMzMzQkAhZmZmZmZ1QCGZmZmZmahAIczMzMzM20AiAAAAAAAOQCIzMzMzM0FAImZmZmZmdEAimZmZmZmnQCLMzMzMzNpAIwAAAAAADUAjMzMzMzNAQCNmZmZmZnNAI5mZmZmZpkAjzMzMzMzZQCQAAAAAAAxAJDMzMzMzP0AkZmZmZmZyQCSZmZmZmaVAJMzMzMzM2EAlAAAAAAALQCUzMzMzMz5AJWZmZmZmcUAlmZmZmZmkQCXMzMzMzNdAJgAAAAAACkAmMzMzMzM9QCZmZmZmZnBAJpmZmZmZo0AmzMzMzMzWQCcAAAAAAAlAJzMzMzMzPEAnZmZmZmZvQCeZmZmZmaJAJ8zMzMzM1UAoAAAAAAAIQCgzMzMzMztAKGZmZmZmbkAomZmZmZmhQCjMzMzMzNRAKQAAAAAAB0ApMzMzMzM6QClmZmZmZm1AKZmZmZmZoEApzMzMzMzTQCoAAAAAAAZAKjMzMzMzOUAqZmZmZmZsQCqZmZmZmZ9AKszMzMzM0kArAAAAAAAFQCszMzMzMzhAK2ZmZmZma0ArmZmZmZmeQCvMzMzMzNFALAAAAAAABEAsMzMzMzM3QCxmZmZmZmpALJmZmZmZnUAszMzMzMzQQC0AAAAAAANALTMzMzMzNkAtZmZmZmZpQC2ZmZmZmZxALczMzMzMz0AuAAAAAAACQC4zMzMzMzVALmZmZmZmaEAumZmZmZmbQC7MzMzMzM5ALwAAAAAAAUAvMzMzMzM0QC9mZmZmZmdAL5mZmZmZmkAvzMzMzMzNQDAAAAAAAABAMBmZmZmZmkAwMzMzMzM0QDBMzMzMzM5AMGZmZmZmaEAwgAAAAAACQDCZmZmZmZxAMLMzMzMzNkAwzMzMzMzQQDDmZmZmZmpAMQAAAAAABEAxGZmZmZmeQDEzMzMzMzhAMUzMzMzM0kAxZmZmZmZsQDGAAAAAAAZAMZmZmZmZoEAxszMzMzM6QDHMzMzMzNRAMeZmZmZmbkAyAAAAAAAIQDIZmZmZmaJAMjMzMzMzPEAyTMzMzMzWQDJmZmZmZnBAMoAAAAAACkAymZmZmZmkQDKzMzMzMz5AMszMzMzM2EAy5mZmZmZyQDMAAAAAAAxAMxmZmZmZpkAzMzMzMzNAQDNMzMzMzNpAM2ZmZmZmdEAzgAAAAAAOQDOZmZmZmahAM7MzMzMzQkAzzMzMzMzcQDPmZmZmZnZANAAAAAAAAA==</DATA>
            <NAME>A2</NAME>
        </ITEM>
        <ITEM type="mem">
            <UNIT>m/s/s</UNIT>
            <DATA>AAAAyQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/+uIfCY1VHkACrcHuMXZbQASa10fR/85ABVAJWMZTLUAFkmwlt+n/QAWqgYo+4KZABbL18RKn10AFtZlYOzpQQAW2B87Y5cxABbWVbdMetkAFtL88r7DfQAWzsz7YZrdABbKCdQ+YZ0AFsTMLzWiWQAWvx2MMcc5ABa5AVkF6gUAFrJ5DQMrAQAWq4UlOdJBABakJeyCb0UAFpxbpZgFiQAWlCZ8cc4ZABaLhpGxRGUAFoJ8E5hW9QAWeQcwBji9ABZvKBY09x0AFmTe9ybJOQAWWiwFwkNNABZPD3br6tUAFkOJgYlQYQAWN5peeOS5ABYrQkkww00AFh6BfgycjQAWEVg6uY6JABYDxsDTkLEAFfXNUzFXZQAV52w2uoJRABWzqVPOnf0AFVH8TG+5AQAU33inRXClABRm7fzi/9EAE+xbVmN1CQATcTyG6hLpABL2HZxf22EAEns0BPd2tQASAJPnrfiFABGGRZuoqckAEQxM69I1DQAQkqwApB7FAA/k9OQ0kBUADt74DxD5bQANucr9TMStAAyLz/TQkX0AC11Wf77OWQAKMXEJ0HtpAAkJPPMy85kAB+Ub7P7tAQAGxSl2cHvNAAWpZ6T1XGkABJHOqTSdgQADflM5Pj69AAJu6Lpb2mUAAWOCRQvOhQAAXBLAirHs//6xGkSR1sD//LHI8kc1uP/6uhe1JJFg//jJ7Q0s4dT/9uEvq9QLEP/0/8aFES28//MlmLwioWD/8VKOF40MNP/vhozOo3bM/+3BfmYlfJT/7ANJ61NFHP/qS9e/mu4k/+ibEHB0jSj/5vDcwehBjP/lTSWfSk+w/+Ov1CK3Q2j/4h4sWK3anP/g51GU8IUQ/9/rBdtVhST/3wV88CoVBP/eKW+AC7AQ/91R8H3rwdD/3H0rLVcHSP/bqnCWv5ws/9rZfsyorTT/2go7eoqVtP/ZPJwGV3FA/9hwmttd6+z/16Y0sbzybP/W3WdIlnrY/9YWL/igKAD/1VCMZl9yjP/UjHpqKURI/9PJ99JZ7xT/0wkCazZLzP/SSZf9LLjo/9GLtlHqMlA==</DATA>
            <NAME>A3</NAME>
        </ITEM>
        <ITEM type="mem">
            <UNIT>s</UNIT>
            <DATA>AAAAyQAAAAAAAAAAP7mZmZmZmao/yZmZmZmZqj/TMzMzMzNAP9mZmZmZmao/4AAAAAAACj/jMzMzMzM/P+ZmZmZmZnQ/6ZmZmZmZqT/szMzMzMzeP/AAAAAAAAo/8ZmZmZmZpT/zMzMzMzNAP/TMzMzMzNs/9mZmZmZmdj/4AAAAAAARP/mZmZmZmaw/+zMzMzMzRz/8zMzMzMziP/5mZmZmZn1AAAAAAAAADEAAzMzMzMzZQAGZmZmZmaZAAmZmZmZmc0ADMzMzMzNAQAQAAAAAAA1ABMzMzMzM2kAFmZmZmZmnQAZmZmZmZnRABzMzMzMzQUAIAAAAAAAOQAjMzMzMzNtACZmZmZmZqEAKZmZmZmZ1QAszMzMzM0JADAAAAAAAD0AMzMzMzMzcQA2ZmZmZmalADmZmZmZmdkAPMzMzMzNDQBAAAAAAAAhAEGZmZmZmb0AQzMzMzMzWQBEzMzMzMz1AEZmZmZmZpEASAAAAAAALQBJmZmZmZnJAEszMzMzM2UATMzMzMzNAQBOZmZmZmadAFAAAAAAADkAUZmZmZmZ1QBTMzMzMzNxAFTMzMzMzQ0AVmZmZmZmqQBYAAAAAABFAFmZmZmZmeEAWzMzMzMzfQBczMzMzM0ZAF5mZmZmZrUAYAAAAAAAUQBhmZmZmZntAGMzMzMzM4kAZMzMzMzNJQBmZmZmZmbBAGgAAAAAAF0AaZmZmZmZ+QBrMzMzMzOVAGzMzMzMzTEAbmZmZmZmzQBwAAAAAABpAHGZmZmZmgUAczMzMzMzoQB0zMzMzM09AHZmZmZmZtkAeAAAAAAAdQB5mZmZmZoRAHszMzMzM60AfMzMzMzNSQB+ZmZmZmblAIAAAAAAAEEAgMzMzMzNDQCBmZmZmZnZAIJmZmZmZqUAgzMzMzMzcQCEAAAAAAA9AITMzMzMzQkAhZmZmZmZ1QCGZmZmZmahAIczMzMzM20AiAAAAAAAOQCIzMzMzM0FAImZmZmZmdEAimZmZmZmnQCLMzMzMzNpAIwAAAAAADUAjMzMzMzNAQCNmZmZmZnNAI5mZmZmZpkAjzMzMzMzZQCQAAAAAAAxAJDMzMzMzP0AkZmZmZmZyQCSZmZmZmaVAJMzMzMzM2EAlAAAAAAALQCUzMzMzMz5AJWZmZmZmcUAlmZmZmZmkQCXMzMzMzNdAJgAAAAAACkAmMzMzMzM9QCZmZmZmZnBAJpmZmZmZo0AmzMzMzMzWQCcAAAAAAAlAJzMzMzMzPEAnZmZmZmZvQCeZmZmZmaJAJ8zMzMzM1UAoAAAAAAAIQCgzMzMzMztAKGZmZmZmbkAomZmZmZmhQCjMzMzMzNRAKQAAAAAAB0ApMzMzMzM6QClmZmZmZm1AKZmZmZmZoEApzMzMzMzTQCoAAAAAAAZAKjMzMzMzOUAqZmZmZmZsQCqZmZmZmZ9AKszMzMzM0kArAAAAAAAFQCszMzMzMzhAK2ZmZmZma0ArmZmZmZmeQCvMzMzMzNFALAAAAAAABEAsMzMzMzM3QCxmZmZmZmpALJmZmZmZnUAszMzMzMzQQC0AAAAAAANALTMzMzMzNkAtZmZmZmZpQC2ZmZmZmZxALczMzMzMz0AuAAAAAAACQC4zMzMzMzVALmZmZmZmaEAumZmZmZmbQC7MzMzMzM5ALwAAAAAAAUAvMzMzMzM0QC9mZmZmZmdAL5mZmZmZmkAvzMzMzMzNQDAAAAAAAABAMBmZmZmZmkAwMzMzMzM0QDBMzMzMzM5AMGZmZmZmaEAwgAAAAAACQDCZmZmZmZxAMLMzMzMzNkAwzMzMzMzQQDDmZmZmZmpAMQAAAAAABEAxGZmZmZmeQDEzMzMzMzhAMUzMzMzM0kAxZmZmZmZsQDGAAAAAAAZAMZmZmZmZoEAxszMzMzM6QDHMzMzMzNRAMeZmZmZmbkAyAAAAAAAIQDIZmZmZmaJAMjMzMzMzPEAyTMzMzMzWQDJmZmZmZnBAMoAAAAAACkAymZmZmZmkQDKzMzMzMz5AMszMzMzM2EAy5mZmZmZyQDMAAAAAAAxAMxmZmZmZpkAzMzMzMzNAQDNMzMzMzNpAM2ZmZmZmdEAzgAAAAAAOQDOZmZmZmahAM7MzMzMzQkAzzMzMzMzcQDPmZmZmZnZANAAAAAAAAA==</DATA>
            <NAME>A4</NAME>
        </ITEM>
        <ITEM type="mem">
            <UNIT>m/s</UNIT>
            <DATA>AAAAyQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/tyZe7jkNyT/Sh2dONp+IP+DqigGRDj8/6Qnz6NmiTT/wqtGGGxpPP/TYvyJJRO4/+QmUejOmGj/9O2Zxh5JrQAC2vpeNQ2ZAAs/I7gn5RUAE6MOcpK74QAcBp6u+jWhACRpw8gtamEALMxxSVEIEQA1Lpw6uMFhAD2QOjz5AXUAQvigkjR7NQBHKNNwZklBAEtYsLTYxiEAT4gzXVKcvQBTt1ZqVJBtAFfmFOBNSMUAXBRpwsYgoQBgQlAYsq9lAGRvwurG/CkAaJy9Q/Lc2QBsyToxcKDVAHD1NMLKx4UAdSCoCfYdRQB5S48bbV81AH115P15PkEAgM/Sd802AQCC5GT80uHhAIT4p5wSVTUAhwyX57LQAQCJIDNy3IwdAIszd89BuS0AjUZTmM8zVQCPWE0ki1NpAJFpBatbpSUAk3hY+fIizQCVhjjR3VDFAJeSnyKJvTUAmZ2I1r/cPQCbpvP7F4GBAJ2u3wrBM60An7VIrILTpQChui+bpF+ZAKO9kp9sjgkApb9lMFBZZQCnvdUl2/FdAKm2LXiNGPkAq6ddm5LeJQCtkRHgg27ZAK9zPO1M85EAsU3rf1vJHQCzITPCNVe9ALTtL0KTBKUAtrH4kCVJRQC4b6pnaruNALomX2Ec34EAu9YxxhOYSQC9fzufkKdRAL8hlp74YIkAwF6uEY+wxQDBKVKeaSG5AMHwxVAWwxkAwrUSVk/iXQDDdkW6mzD5AMQ0a17g+eEAxO+O/uiCsQDFp7wle/PZAMZc/kCQEB0Axw9gkxP3eQDHvu44Qbf9AMhrsieuAVEAyRW3OEmjmQDJvQgPfjXlAMphrzCu2GUAywO2+dAsnQDLoynoapJdAMxAI/A0ackAzNsqSXxZiQDNdJvo+gdxAM4Mnew7+vkAzqM/tUiMkQDPOIi+GoGBAM/MfWH5IFEA0F8g5jYG6QDQ8HYn2/ylANGAf+gcPlkA0g9AzKITGQDSnLtT8aKFANMo8eLFF3UA07PnOG7KBQDUPZ3ilZCFANTGGGLkXskA1U1ZOlcI4QDV02LnUJzdANZYN+Say8g==</DATA>
            <NAME>A5</NAME>
        </ITEM>
        <ITEM type="mem">
            <UNIT>s</UNIT>
            <DATA>AAAAyQAAAAAAAAAAP7mZmZmZmao/yZmZmZmZqj/TMzMzMzNAP9mZmZmZmao/4AAAAAAACj/jMzMzMzM/P+ZmZmZmZnQ/6ZmZmZmZqT/szMzMzMzeP/AAAAAAAAo/8ZmZmZmZpT/zMzMzMzNAP/TMzMzMzNs/9mZmZmZmdj/4AAAAAAARP/mZmZmZmaw/+zMzMzMzRz/8zMzMzMziP/5mZmZmZn1AAAAAAAAADEAAzMzMzMzZQAGZmZmZmaZAAmZmZmZmc0ADMzMzMzNAQAQAAAAAAA1ABMzMzMzM2kAFmZmZmZmnQAZmZmZmZnRABzMzMzMzQUAIAAAAAAAOQAjMzMzMzNtACZmZmZmZqEAKZmZmZmZ1QAszMzMzM0JADAAAAAAAD0AMzMzMzMzcQA2ZmZmZmalADmZmZmZmdkAPMzMzMzNDQBAAAAAAAAhAEGZmZmZmb0AQzMzMzMzWQBEzMzMzMz1AEZmZmZmZpEASAAAAAAALQBJmZmZmZnJAEszMzMzM2UATMzMzMzNAQBOZmZmZmadAFAAAAAAADkAUZmZmZmZ1QBTMzMzMzNxAFTMzMzMzQ0AVmZmZmZmqQBYAAAAAABFAFmZmZmZmeEAWzMzMzMzfQBczMzMzM0ZAF5mZmZmZrUAYAAAAAAAUQBhmZmZmZntAGMzMzMzM4kAZMzMzMzNJQBmZmZmZmbBAGgAAAAAAF0AaZmZmZmZ+QBrMzMzMzOVAGzMzMzMzTEAbmZmZmZmzQBwAAAAAABpAHGZmZmZmgUAczMzMzMzoQB0zMzMzM09AHZmZmZmZtkAeAAAAAAAdQB5mZmZmZoRAHszMzMzM60AfMzMzMzNSQB+ZmZmZmblAIAAAAAAAEEAgMzMzMzNDQCBmZmZmZnZAIJmZmZmZqUAgzMzMzMzcQCEAAAAAAA9AITMzMzMzQkAhZmZmZmZ1QCGZmZmZmahAIczMzMzM20AiAAAAAAAOQCIzMzMzM0FAImZmZmZmdEAimZmZmZmnQCLMzMzMzNpAIwAAAAAADUAjMzMzMzNAQCNmZmZmZnNAI5mZmZmZpkAjzMzMzMzZQCQAAAAAAAxAJDMzMzMzP0AkZmZmZmZyQCSZmZmZmaVAJMzMzMzM2EAlAAAAAAALQCUzMzMzMz5AJWZmZmZmcUAlmZmZmZmkQCXMzMzMzNdAJgAAAAAACkAmMzMzMzM9QCZmZmZmZnBAJpmZmZmZo0AmzMzMzMzWQCcAAAAAAAlAJzMzMzMzPEAnZmZmZmZvQCeZmZmZmaJAJ8zMzMzM1UAoAAAAAAAIQCgzMzMzMztAKGZmZmZmbkAomZmZmZmhQCjMzMzMzNRAKQAAAAAAB0ApMzMzMzM6QClmZmZmZm1AKZmZmZmZoEApzMzMzMzTQCoAAAAAAAZAKjMzMzMzOUAqZmZmZmZsQCqZmZmZmZ9AKszMzMzM0kArAAAAAAAFQCszMzMzMzhAK2ZmZmZma0ArmZmZmZmeQCvMzMzMzNFALAAAAAAABEAsMzMzMzM3QCxmZmZmZmpALJmZmZmZnUAszMzMzMzQQC0AAAAAAANALTMzMzMzNkAtZmZmZmZpQC2ZmZmZmZxALczMzMzMz0AuAAAAAAACQC4zMzMzMzVALmZmZmZmaEAumZmZmZmbQC7MzMzMzM5ALwAAAAAAAUAvMzMzMzM0QC9mZmZmZmdAL5mZmZmZmkAvzMzMzMzNQDAAAAAAAABAMBmZmZmZmkAwMzMzMzM0QDBMzMzMzM5AMGZmZmZmaEAwgAAAAAACQDCZmZmZmZxAMLMzMzMzNkAwzMzMzMzQQDDmZmZmZmpAMQAAAAAABEAxGZmZmZmeQDEzMzMzMzhAMUzMzMzM0kAxZmZmZmZsQDGAAAAAAAZAMZmZmZmZoEAxszMzMzM6QDHMzMzMzNRAMeZmZmZmbkAyAAAAAAAIQDIZmZmZmaJAMjMzMzMzPEAyTMzMzMzWQDJmZmZmZnBAMoAAAAAACkAymZmZmZmkQDKzMzMzMz5AMszMzMzM2EAy5mZmZmZyQDMAAAAAAAxAMxmZmZmZpkAzMzMzMzNAQDNMzMzMzNpAM2ZmZmZmdEAzgAAAAAAOQDOZmZmZmahAM7MzMzMzQkAzzMzMzMzcQDPmZmZmZnZANAAAAAAAAA==</DATA>
            <NAME>A6</NAME>
        </ITEM>
        <ITEM type="mem">
            <UNIT>m/s</UNIT>
            <DATA>AAAAyQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/uAL7I9klLj/TMc5RoEYlP+GEZm45oAc/6eyHRT2liD/xQTTYQa2LP/WUgP0+p10/+erM8mx/Nz/+QhzmVbK0QAFM2U/8pqlAA3iiWUue40AFpFpay+wOQAfP+ghI2pZACft8/BjwdEAMJt/mp2pSQA5SH9pWo9JAED6dCI2MJkARVBXpIgyfQBJpeTYcCWlAE37Fl8FgMEAUk/m26oXMQBWpFDkYyaVAFr4T0dW0YUAX0vcl7iZEQBjnvOEVE4FAGfxjr3NhfEAbEOo9b/VfQBwlTzgK2O9AHTmRTPWxIEAeTa8qljVUQB9hp4ABc8tAIDq8d7H2dkAgxJEaDUzEQCFOUQsr7NlAIdf7mlz1rEAiYZAfYrRMQCLrDfFVsyNAI3RgRQmDckAj/TUXLzoNQCSFXe3gRalAJQzJ5RhQckAlk3MQWyZ0QCYZV494HcxAJp53BePaIEAnItGkZ/Q6QCemZ9M4u31AKCk6D3WmtUAoq0jfbmLwQCkslM5I8GJAKa0FlKFoXkAqLA96Iv/SQCqpWKLb5UJAKyTD8TweKEArnksMcA3ZQCwV8Af2/PFALIu4C/iSoEAs/6leo279QC1xyqBAQxJALeIihZEeNkAuULe9Nw43QC69kOYs8U5ALyi0jNt75kAvkikmCkv3QC/59RV9ivZAMDAPVGUY+0AwYlYLU0SVQDCT0cQ4/rNAMMSFhe2D+UAw9HROLUFRQDEjoQ8ImOhAMVIOsi+Tl0Axf8AMwZ29QDGsuBaMOo5AMdj5cJtqTUAyBIb14diBQDIvY1wuinRAMlmRUVVWVUAygxN6QWNaQDKr7HSQFFlAMtQe1e6JMkAy+61DohnJQDMiq10Y7Q1AM0k6r74H5UAzb2pUDHurQDOVQE6MYfdAM7q/RSIHWkAz3+idhj+jQDQEvUY0FFJANCk+ANuOD0A0TWt+XU+2QDRxRmp0cuJANJTPb/Nd5EA0uAcxOvw/QDTa7kI8m+FANP2FT9pSF0A1H80AfeMOQDVBxfPmIJVANWNwygByzUA1hM4h1VFkQDWl3pm82GRANcaizr07gg==</DATA>
            <NAME>A7</NAME>
        </ITEM>
    </ITEMS_LIST>
    <INPUT_ITEMS_LIST/>
    <COMPUTATION_LIST/>
    <PAGE_CFG>
        <WINDOW_SIZE>1210 674</WINDOW_SIZE>
        <NB_ROWS_COLUMNS>1 2</NB_ROWS_COLUMNS>
        <AREAS_LIST>
            <AREA>
                <GEOMETRY>0 0 604 577</GEOMETRY>
                <GRAPH_RENDERER type="2D Graph">
                    <MARGIN_COLOR>255 255 255</MARGIN_COLOR>
                    <MARGIN_SIZE>46 43 3 31 56 0 56 56</MARGIN_SIZE>
                    <AREA_COLOR>255 255 255</AREA_COLOR>
                    <IS_BOX_DRAWN>true</IS_BOX_DRAWN>
                    <BOX_PEN>200 200 200 1 1</BOX_PEN>
                    <X_AXIS>
                        <ZOOM/>
                        <TITLE>
                            <SHOW_BORDER>false</SHOW_BORDER>
                            <GRAPH_ANCHOR>13</GRAPH_ANCHOR>
                            <RGB_FG_COLOR>0 0 0</RGB_FG_COLOR>
                            <FONT_FAMILY>MS Shell Dlg 2</FONT_FAMILY>
                            <FONT_SIZE>8</FONT_SIZE>
                            <FONT_STYLE>50 0</FONT_STYLE>
                            <FONT_EFFECT>0 0</FONT_EFFECT>
                        </TITLE>
                        <PEN>0 0 0 1 1</PEN>
                        <FONT>
                            <FONT_FAMILY>Segoe UI</FONT_FAMILY>
                            <FONT_SIZE>8</FONT_SIZE>
                            <FONT_STYLE>75 0</FONT_STYLE>
                            <FONT_EFFECT>0 0</FONT_EFFECT>
                        </FONT>
                        <OPTIONS>
                            <POWER_MODE>-1</POWER_MODE>
                            <MAJOR_TICKS_MODE>-1</MAJOR_TICKS_MODE>
                            <MINOR_TICKS_MODE>-1</MINOR_TICKS_MODE>
                        </OPTIONS>
                        <SHOW_LINES>true</SHOW_LINES>
                        <SHOW_TEXTS>true</SHOW_TEXTS>
                        <SHOW_UNIT>false</SHOW_UNIT>
                        <SHOW_TITLE>true</SHOW_TITLE>
                        <DRAW_AXIS>true</DRAW_AXIS>
                        <MAJOR_GRID_PEN>200 200 200 3 1</MAJOR_GRID_PEN>
                        <MINOR_GRID_STYLE>3</MINOR_GRID_STYLE>
                        <MAJOR_GRID_DRAWN>true</MAJOR_GRID_DRAWN>
                        <MINOR_GRID_DRAWN>true</MINOR_GRID_DRAWN>
                    </X_AXIS>
                    <Y_AXIS>
                        <ZOOM/>
                        <TITLE>
                            <SHOW_BORDER>false</SHOW_BORDER>
                            <GRAPH_ANCHOR>18</GRAPH_ANCHOR>
                            <RGB_FG_COLOR>0 0 0</RGB_FG_COLOR>
                            <FONT_FAMILY>MS Shell Dlg 2</FONT_FAMILY>
                            <FONT_SIZE>8</FONT_SIZE>
                            <FONT_STYLE>50 0</FONT_STYLE>
                            <FONT_EFFECT>0 0</FONT_EFFECT>
                        </TITLE>
                        <PEN>0 0 0 1 1</PEN>
                        <FONT>
                            <FONT_FAMILY>Segoe UI</FONT_FAMILY>
                            <FONT_SIZE>8</FONT_SIZE>
                            <FONT_STYLE>75 0</FONT_STYLE>
                            <FONT_EFFECT>0 0</FONT_EFFECT>
                        </FONT>
                        <RANK>0</RANK>
                        <OPTIONS>
                            <POWER_MODE>-1</POWER_MODE>
                            <MAJOR_TICKS_MODE>-1</MAJOR_TICKS_MODE>
                            <MINOR_TICKS_MODE>-1</MINOR_TICKS_MODE>
                        </OPTIONS>
                        <SHOW_LINES>true</SHOW_LINES>
                        <SHOW_TEXTS>true</SHOW_TEXTS>
                        <SHOW_UNIT>true</SHOW_UNIT>
                        <SHOW_TITLE>false</SHOW_TITLE>
                        <DRAW_AXIS>true</DRAW_AXIS>
                        <MAJOR_GRID_PEN>200 200 200 3 1</MAJOR_GRID_PEN>
                        <MINOR_GRID_STYLE>3</MINOR_GRID_STYLE>
                        <MAJOR_GRID_DRAWN>true</MAJOR_GRID_DRAWN>
                        <MINOR_GRID_DRAWN>true</MINOR_GRID_DRAWN>
                    </Y_AXIS>
                </GRAPH_RENDERER>
                <CURVE type="2D curve">
                    <TITLE>
                        <RGB_FG_COLOR>0 0 0</RGB_FG_COLOR>
                        <FONT_FAMILY>MS Shell Dlg 2</FONT_FAMILY>
                        <FONT_SIZE>8</FONT_SIZE>
                        <FONT_STYLE>50 0</FONT_STYLE>
                        <FONT_EFFECT>0 0</FONT_EFFECT>
                    </TITLE>
                    <ITEM>
                        <NAME>A0</NAME>
                    </ITEM>
                    <ITEM>
                        <NAME>A1</NAME>
                    </ITEM>
                    <CURVE_DISPLAY type="2D line">
                        <ARE_LINES_DRAWN>true</ARE_LINES_DRAWN>
                        <LINE_PEN>237 11 0 1 2 1</LINE_PEN>
                        <ARE_SYMBOLS_DRAWN>false</ARE_SYMBOLS_DRAWN>
                        <SYMBOLS_COLOR>237 11 0</SYMBOLS_COLOR>
                        <SYMBOLS_STYLE>4</SYMBOLS_STYLE>
                        <SYMBOLS_SIZE>1</SYMBOLS_SIZE>
                        <SYMBOLS_DENSITY>100</SYMBOLS_DENSITY>
                        <ARE_Z_SYMBOLS_DRAWN>true</ARE_Z_SYMBOLS_DRAWN>
                        <USER_CUSTOM_COLOR>true</USER_CUSTOM_COLOR>
                    </CURVE_DISPLAY>
                    <META_DATA>AAAAAgAAACQAVgBhAHIAaQBhAGIAbABlAEkAZABlAG4AdABpAGYAaQBlAHIAAAAKAAAAATQAewBQAEUAUgBGAE8AUgBNAEEATgBDAEUAXwBTAFQAVQBEAFkAOwBTAHQAdQBkAHkAOwBEAGUAZgBpAG4AaQB0AGkAbwBuAH0ALgB7AFIAVQBOAF8AUABFAFIARgBfAE0AMQBfAEIAMQA7AFIAdQBuADsAUwB0AGEAbgBkAGEAbABvAG4AZQB9AC4AewBWAEUASABJAEMATABFAF8AMQBEADsASQBuAHMAdAByAHUAbQBlAG4AdABlAGQAUwB1AGIAbQBvAGQAZQBsADsASQBuAHMAdABhAG4AYwBlAH0ALgB7AGEAYwBjAGUAbABlAHIAYQB0AGkAbwBuADsAVgBhAHIAaQBhAGIAbABlAEUAeABwAG8AcwB1AHIAZQA7AFMAdABhAG4AZABhAGwAbwBuAGUAfQAAACYAQwBvAG4AdABhAGkAbgBlAHIASQBkAGUAbgB0AGkAZgBpAGUAcgAAAAoAAAAA3gB7AFAARQBSAEYATwBSAE0AQQBOAEMARQBfAFMAVABVAEQAWQA7AFMAdAB1AGQAeQA7AEQAZQBmAGkAbgBpAHQAaQBvAG4AfQAuAHsAUgBVAE4AXwBQAEUAUgBGAF8ATQAxAF8AQgAxADsAUgB1AG4AOwBTAHQAYQBuAGQAYQBsAG8AbgBlAH0ALgB7AFYARQBIAEkAQwBMAEUAXwAxAEQAOwBJAG4AcwB0AHIAdQBtAGUAbgB0AGUAZABTAHUAYgBtAG8AZABlAGwAOwBJAG4AcwB0AGEAbgBjAGUAfQ==</META_DATA>
                    <YAXIS_RANK>0 0</YAXIS_RANK>
                </CURVE>
                <CURVE type="2D curve">
                    <TITLE>
                        <RGB_FG_COLOR>0 0 0</RGB_FG_COLOR>
                        <FONT_FAMILY>MS Shell Dlg 2</FONT_FAMILY>
                        <FONT_SIZE>8</FONT_SIZE>
                        <FONT_STYLE>50 0</FONT_STYLE>
                        <FONT_EFFECT>0 0</FONT_EFFECT>
                    </TITLE>
                    <ITEM>
                        <NAME>A2</NAME>
                    </ITEM>
                    <ITEM>
                        <NAME>A3</NAME>
                    </ITEM>
                    <CURVE_DISPLAY type="2D line">
                        <ARE_LINES_DRAWN>true</ARE_LINES_DRAWN>
                        <LINE_PEN>0 100 135 1 2 1</LINE_PEN>
                        <ARE_SYMBOLS_DRAWN>false</ARE_SYMBOLS_DRAWN>
                        <SYMBOLS_COLOR>0 100 135</SYMBOLS_COLOR>
                        <SYMBOLS_STYLE>4</SYMBOLS_STYLE>
                        <SYMBOLS_SIZE>1</SYMBOLS_SIZE>
                        <SYMBOLS_DENSITY>100</SYMBOLS_DENSITY>
                        <ARE_Z_SYMBOLS_DRAWN>true</ARE_Z_SYMBOLS_DRAWN>
                        <USER_CUSTOM_COLOR>true</USER_CUSTOM_COLOR>
                    </CURVE_DISPLAY>
                    <META_DATA>AAAAAgAAACQAVgBhAHIAaQBhAGIAbABlAEkAZABlAG4AdABpAGYAaQBlAHIAAAAKAAAAATQAewBQAEUAUgBGAE8AUgBNAEEATgBDAEUAXwBTAFQAVQBEAFkAOwBTAHQAdQBkAHkAOwBEAGUAZgBpAG4AaQB0AGkAbwBuAH0ALgB7AFIAVQBOAF8AUABFAFIARgBfAE0AMgBfAEIAMQA7AFIAdQBuADsAUwB0AGEAbgBkAGEAbABvAG4AZQB9AC4AewBWAEUASABJAEMATABFAF8AMQBEADsASQBuAHMAdAByAHUAbQBlAG4AdABlAGQAUwB1AGIAbQBvAGQAZQBsADsASQBuAHMAdABhAG4AYwBlAH0ALgB7AGEAYwBjAGUAbABlAHIAYQB0AGkAbwBuADsAVgBhAHIAaQBhAGIAbABlAEUAeABwAG8AcwB1AHIAZQA7AFMAdABhAG4AZABhAGwAbwBuAGUAfQAAACYAQwBvAG4AdABhAGkAbgBlAHIASQBkAGUAbgB0AGkAZgBpAGUAcgAAAAoAAAAA3gB7AFAARQBSAEYATwBSAE0AQQBOAEMARQBfAFMAVABVAEQAWQA7AFMAdAB1AGQAeQA7AEQAZQBmAGkAbgBpAHQAaQBvAG4AfQAuAHsAUgBVAE4AXwBQAEUAUgBGAF8ATQAyAF8AQgAxADsAUgB1AG4AOwBTAHQAYQBuAGQAYQBsAG8AbgBlAH0ALgB7AFYARQBIAEkAQwBMAEUAXwAxAEQAOwBJAG4AcwB0AHIAdQBtAGUAbgB0AGUAZABTAHUAYgBtAG8AZABlAGwAOwBJAG4AcwB0AGEAbgBjAGUAfQ==</META_DATA>
                    <YAXIS_RANK>0 0</YAXIS_RANK>
                </CURVE>
                <GRAPH_TITLES_CONFIGURATION>
                    <IS_AUTOMATIC_MODE>0</IS_AUTOMATIC_MODE>
                    <IS_GRAPH_TITLE_SHOWN>false</IS_GRAPH_TITLE_SHOWN>
                    <IS_LEGEND_SHOWN>true</IS_LEGEND_SHOWN>
                    <IS_GRAPH_KEYS_SHOWN>false</IS_GRAPH_KEYS_SHOWN>
                    <LEGEND_POSITION>16</LEGEND_POSITION>
                    <TITLE_POSITION>2</TITLE_POSITION>
                    <X_AXIS_TITLE_POSITION>13</X_AXIS_TITLE_POSITION>
                </GRAPH_TITLES_CONFIGURATION>
                <GRAPH_TITLE>
                    <SHOW_BORDER>false</SHOW_BORDER>
                    <GRAPH_ANCHOR>2</GRAPH_ANCHOR>
                    <RGB_FG_COLOR>0 0 0</RGB_FG_COLOR>
                    <FONT_FAMILY>MS Shell Dlg 2</FONT_FAMILY>
                    <FONT_SIZE>8</FONT_SIZE>
                    <FONT_STYLE>75 0</FONT_STYLE>
                    <FONT_EFFECT>0 0</FONT_EFFECT>
                </GRAPH_TITLE>
                <LEGEND>
                    <SHOW_BORDER>true</SHOW_BORDER>
                    <GRAPH_ANCHOR>16</GRAPH_ANCHOR>
                    <DEFAULT_TEXT_STYLE>
                        <COLOR>0 0 0</COLOR>
                        <FONT>
                            <FONT_FAMILY>MS Shell Dlg 2</FONT_FAMILY>
                            <FONT_SIZE>8</FONT_SIZE>
                            <FONT_STYLE>50 0</FONT_STYLE>
                            <FONT_EFFECT>0 0</FONT_EFFECT>
                        </FONT>
                        <BORDER_SHOWN>true</BORDER_SHOWN>
                    </DEFAULT_TEXT_STYLE>
                </LEGEND>
            </AREA>
            <AREA>
                <GEOMETRY>604 0 604 577</GEOMETRY>
                <GRAPH_RENDERER type="2D Graph">
                    <MARGIN_COLOR>255 255 255</MARGIN_COLOR>
                    <MARGIN_SIZE>46 43 3 31 56 0 56 56</MARGIN_SIZE>
                    <AREA_COLOR>255 255 255</AREA_COLOR>
                    <IS_BOX_DRAWN>true</IS_BOX_DRAWN>
                    <BOX_PEN>200 200 200 1 1</BOX_PEN>
                    <X_AXIS>
                        <ZOOM/>
                        <TITLE>
                            <SHOW_BORDER>false</SHOW_BORDER>
                            <GRAPH_ANCHOR>13</GRAPH_ANCHOR>
                            <RGB_FG_COLOR>0 0 0</RGB_FG_COLOR>
                            <FONT_FAMILY>MS Shell Dlg 2</FONT_FAMILY>
                            <FONT_SIZE>8</FONT_SIZE>
                            <FONT_STYLE>50 0</FONT_STYLE>
                            <FONT_EFFECT>0 0</FONT_EFFECT>
                        </TITLE>
                        <PEN>0 0 0 1 1</PEN>
                        <FONT>
                            <FONT_FAMILY>Segoe UI</FONT_FAMILY>
                            <FONT_SIZE>8</FONT_SIZE>
                            <FONT_STYLE>75 0</FONT_STYLE>
                            <FONT_EFFECT>0 0</FONT_EFFECT>
                        </FONT>
                        <OPTIONS>
                            <POWER_MODE>-1</POWER_MODE>
                            <MAJOR_TICKS_MODE>-1</MAJOR_TICKS_MODE>
                            <MINOR_TICKS_MODE>-1</MINOR_TICKS_MODE>
                        </OPTIONS>
                        <SHOW_LINES>true</SHOW_LINES>
                        <SHOW_TEXTS>true</SHOW_TEXTS>
                        <SHOW_UNIT>false</SHOW_UNIT>
                        <SHOW_TITLE>true</SHOW_TITLE>
                        <DRAW_AXIS>true</DRAW_AXIS>
                        <MAJOR_GRID_PEN>200 200 200 3 1</MAJOR_GRID_PEN>
                        <MINOR_GRID_STYLE>3</MINOR_GRID_STYLE>
                        <MAJOR_GRID_DRAWN>true</MAJOR_GRID_DRAWN>
                        <MINOR_GRID_DRAWN>true</MINOR_GRID_DRAWN>
                    </X_AXIS>
                    <Y_AXIS>
                        <ZOOM/>
                        <TITLE>
                            <SHOW_BORDER>false</SHOW_BORDER>
                            <GRAPH_ANCHOR>18</GRAPH_ANCHOR>
                            <RGB_FG_COLOR>0 0 0</RGB_FG_COLOR>
                            <FONT_FAMILY>MS Shell Dlg 2</FONT_FAMILY>
                            <FONT_SIZE>8</FONT_SIZE>
                            <FONT_STYLE>50 0</FONT_STYLE>
                            <FONT_EFFECT>0 0</FONT_EFFECT>
                        </TITLE>
                        <PEN>0 0 0 1 1</PEN>
                        <FONT>
                            <FONT_FAMILY>Segoe UI</FONT_FAMILY>
                            <FONT_SIZE>8</FONT_SIZE>
                            <FONT_STYLE>75 0</FONT_STYLE>
                            <FONT_EFFECT>0 0</FONT_EFFECT>
                        </FONT>
                        <RANK>0</RANK>
                        <OPTIONS>
                            <POWER_MODE>-1</POWER_MODE>
                            <MAJOR_TICKS_MODE>-1</MAJOR_TICKS_MODE>
                            <MINOR_TICKS_MODE>-1</MINOR_TICKS_MODE>
                        </OPTIONS>
                        <SHOW_LINES>true</SHOW_LINES>
                        <SHOW_TEXTS>true</SHOW_TEXTS>
                        <SHOW_UNIT>true</SHOW_UNIT>
                        <SHOW_TITLE>false</SHOW_TITLE>
                        <DRAW_AXIS>true</DRAW_AXIS>
                        <MAJOR_GRID_PEN>200 200 200 3 1</MAJOR_GRID_PEN>
                        <MINOR_GRID_STYLE>3</MINOR_GRID_STYLE>
                        <MAJOR_GRID_DRAWN>true</MAJOR_GRID_DRAWN>
                        <MINOR_GRID_DRAWN>true</MINOR_GRID_DRAWN>
                    </Y_AXIS>
                </GRAPH_RENDERER>
                <CURVE type="2D curve">
                    <TITLE>
                        <RGB_FG_COLOR>0 0 0</RGB_FG_COLOR>
                        <FONT_FAMILY>MS Shell Dlg 2</FONT_FAMILY>
                        <FONT_SIZE>8</FONT_SIZE>
                        <FONT_STYLE>50 0</FONT_STYLE>
                        <FONT_EFFECT>0 0</FONT_EFFECT>
                    </TITLE>
                    <ITEM>
                        <NAME>A4</NAME>
                    </ITEM>
                    <ITEM>
                        <NAME>A5</NAME>
                    </ITEM>
                    <CURVE_DISPLAY type="2D line">
                        <ARE_LINES_DRAWN>true</ARE_LINES_DRAWN>
                        <LINE_PEN>250 165 10 1 2 1</LINE_PEN>
                        <ARE_SYMBOLS_DRAWN>false</ARE_SYMBOLS_DRAWN>
                        <SYMBOLS_COLOR>250 165 10</SYMBOLS_COLOR>
                        <SYMBOLS_STYLE>4</SYMBOLS_STYLE>
                        <SYMBOLS_SIZE>1</SYMBOLS_SIZE>
                        <SYMBOLS_DENSITY>100</SYMBOLS_DENSITY>
                        <ARE_Z_SYMBOLS_DRAWN>true</ARE_Z_SYMBOLS_DRAWN>
                        <USER_CUSTOM_COLOR>true</USER_CUSTOM_COLOR>
                    </CURVE_DISPLAY>
                    <META_DATA>AAAAAgAAACQAVgBhAHIAaQBhAGIAbABlAEkAZABlAG4AdABpAGYAaQBlAHIAAAAKAAAAATAAewBQAEUAUgBGAE8AUgBNAEEATgBDAEUAXwBTAFQAVQBEAFkAOwBTAHQAdQBkAHkAOwBEAGUAZgBpAG4AaQB0AGkAbwBuAH0ALgB7AFIAVQBOAF8AUABFAFIARgBfAE0AMQBfAEIAMQA7AFIAdQBuADsAUwB0AGEAbgBkAGEAbABvAG4AZQB9AC4AewBWAEUASABJAEMATABFAF8AMQBEADsASQBuAHMAdAByAHUAbQBlAG4AdABlAGQAUwB1AGIAbQBvAGQAZQBsADsASQBuAHMAdABhAG4AYwBlAH0ALgB7AHYAZQBsAG8AYwBpAHQAeQBfADEAOwBWAGEAcgBpAGEAYgBsAGUARQB4AHAAbwBzAHUAcgBlADsAUwB0AGEAbgBkAGEAbABvAG4AZQB9AAAAJgBDAG8AbgB0AGEAaQBuAGUAcgBJAGQAZQBuAHQAaQBmAGkAZQByAAAACgAAAADeAHsAUABFAFIARgBPAFIATQBBAE4AQwBFAF8AUwBUAFUARABZADsAUwB0AHUAZAB5ADsARABlAGYAaQBuAGkAdABpAG8AbgB9AC4AewBSAFUATgBfAFAARQBSAEYAXwBNADEAXwBCADEAOwBSAHUAbgA7AFMAdABhAG4AZABhAGwAbwBuAGUAfQAuAHsAVgBFAEgASQBDAEwARQBfADEARAA7AEkAbgBzAHQAcgB1AG0AZQBuAHQAZQBkAFMAdQBiAG0AbwBkAGUAbAA7AEkAbgBzAHQAYQBuAGMAZQB9</META_DATA>
                    <YAXIS_RANK>0 0</YAXIS_RANK>
                </CURVE>
                <CURVE type="2D curve">
                    <TITLE>
                        <RGB_FG_COLOR>0 0 0</RGB_FG_COLOR>
                        <FONT_FAMILY>MS Shell Dlg 2</FONT_FAMILY>
                        <FONT_SIZE>8</FONT_SIZE>
                        <FONT_STYLE>50 0</FONT_STYLE>
                        <FONT_EFFECT>0 0</FONT_EFFECT>
                    </TITLE>
                    <ITEM>
                        <NAME>A6</NAME>
                    </ITEM>
                    <ITEM>
                        <NAME>A7</NAME>
                    </ITEM>
                    <CURVE_DISPLAY type="2D line">
                        <ARE_LINES_DRAWN>true</ARE_LINES_DRAWN>
                        <LINE_PEN>0 100 135 1 2 1</LINE_PEN>
                        <ARE_SYMBOLS_DRAWN>false</ARE_SYMBOLS_DRAWN>
                        <SYMBOLS_COLOR>0 100 135</SYMBOLS_COLOR>
                        <SYMBOLS_STYLE>4</SYMBOLS_STYLE>
                        <SYMBOLS_SIZE>1</SYMBOLS_SIZE>
                        <SYMBOLS_DENSITY>100</SYMBOLS_DENSITY>
                        <ARE_Z_SYMBOLS_DRAWN>true</ARE_Z_SYMBOLS_DRAWN>
                        <USER_CUSTOM_COLOR>true</USER_CUSTOM_COLOR>
                    </CURVE_DISPLAY>
                    <META_DATA>AAAAAgAAACQAVgBhAHIAaQBhAGIAbABlAEkAZABlAG4AdABpAGYAaQBlAHIAAAAKAAAAATAAewBQAEUAUgBGAE8AUgBNAEEATgBDAEUAXwBTAFQAVQBEAFkAOwBTAHQAdQBkAHkAOwBEAGUAZgBpAG4AaQB0AGkAbwBuAH0ALgB7AFIAVQBOAF8AUABFAFIARgBfAE0AMgBfAEIAMQA7AFIAdQBuADsAUwB0AGEAbgBkAGEAbABvAG4AZQB9AC4AewBWAEUASABJAEMATABFAF8AMQBEADsASQBuAHMAdAByAHUAbQBlAG4AdABlAGQAUwB1AGIAbQBvAGQAZQBsADsASQBuAHMAdABhAG4AYwBlAH0ALgB7AHYAZQBsAG8AYwBpAHQAeQBfADEAOwBWAGEAcgBpAGEAYgBsAGUARQB4AHAAbwBzAHUAcgBlADsAUwB0AGEAbgBkAGEAbABvAG4AZQB9AAAAJgBDAG8AbgB0AGEAaQBuAGUAcgBJAGQAZQBuAHQAaQBmAGkAZQByAAAACgAAAADeAHsAUABFAFIARgBPAFIATQBBAE4AQwBFAF8AUwBUAFUARABZADsAUwB0AHUAZAB5ADsARABlAGYAaQBuAGkAdABpAG8AbgB9AC4AewBSAFUATgBfAFAARQBSAEYAXwBNADIAXwBCADEAOwBSAHUAbgA7AFMAdABhAG4AZABhAGwAbwBuAGUAfQAuAHsAVgBFAEgASQBDAEwARQBfADEARAA7AEkAbgBzAHQAcgB1AG0AZQBuAHQAZQBkAFMAdQBiAG0AbwBkAGUAbAA7AEkAbgBzAHQAYQBuAGMAZQB9</META_DATA>
                    <YAXIS_RANK>0 0</YAXIS_RANK>
                </CURVE>
                <GRAPH_TITLES_CONFIGURATION>
                    <IS_AUTOMATIC_MODE>0</IS_AUTOMATIC_MODE>
                    <IS_GRAPH_TITLE_SHOWN>false</IS_GRAPH_TITLE_SHOWN>
                    <IS_LEGEND_SHOWN>true</IS_LEGEND_SHOWN>
                    <IS_GRAPH_KEYS_SHOWN>false</IS_GRAPH_KEYS_SHOWN>
                    <LEGEND_POSITION>16</LEGEND_POSITION>
                    <TITLE_POSITION>2</TITLE_POSITION>
                    <X_AXIS_TITLE_POSITION>13</X_AXIS_TITLE_POSITION>
                </GRAPH_TITLES_CONFIGURATION>
                <GRAPH_TITLE>
                    <SHOW_BORDER>false</SHOW_BORDER>
                    <GRAPH_ANCHOR>2</GRAPH_ANCHOR>
                    <RGB_FG_COLOR>0 0 0</RGB_FG_COLOR>
                    <FONT_FAMILY>MS Shell Dlg 2</FONT_FAMILY>
                    <FONT_SIZE>8</FONT_SIZE>
                    <FONT_STYLE>75 0</FONT_STYLE>
                    <FONT_EFFECT>0 0</FONT_EFFECT>
                </GRAPH_TITLE>
                <LEGEND>
                    <SHOW_BORDER>true</SHOW_BORDER>
                    <GRAPH_ANCHOR>16</GRAPH_ANCHOR>
                    <DEFAULT_TEXT_STYLE>
                        <COLOR>0 0 0</COLOR>
                        <FONT>
                            <FONT_FAMILY>MS Shell Dlg 2</FONT_FAMILY>
                            <FONT_SIZE>8</FONT_SIZE>
                            <FONT_STYLE>50 0</FONT_STYLE>
                            <FONT_EFFECT>0 0</FONT_EFFECT>
                        </FONT>
                        <BORDER_SHOWN>true</BORDER_SHOWN>
                    </DEFAULT_TEXT_STYLE>
                </LEGEND>
            </AREA>
        </AREAS_LIST>
    </PAGE_CFG>
</PLT_API>
